kind: pipeline
name: default

steps:
  - name: test 
    image: python:3.10-slim 
    commands:
      - pip3 install poetry
      - poetry install --with test
      - poetry run pytest
  - name: docker
    image: plugins/docker
    settings:
      registry: registry.gitlab.com
      username:
        from_secret: docker_registry_username
      password:
        from_secret: docker_registry_password
      repo: registry.gitlab.com/codegiik/flaskdir
      auto_tag: true
